project_name: tofu

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make protobuf

builds:
  - env:
      - CGO_ENABLED=0

    main: ./cmd/tofu

    flags:
      - "-mod=readonly"
      - "-trimpath"

    ldflags:
      - "-s -w"
      - "-X 'github.com/liatrio/opentofu/version.dev=no'"

    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"

dockers:
  - use: buildx
    goarch: amd64
    goos: linux
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.vendor=OpenTofu"
      - "--label=org.opencontainers.image.description=OpenTofu {{ .Version }}"
      - "--label=org.opencontainers.image.url=https://github.com/liatrio/opentofu"
      - "--label=org.opencontainers.image.documentation=https://github.com/liatrio/opentofu/blob/main/README.md"
      - "--label=org.opencontainers.image.source=https://github.com/liatrio/opentofu"
      - "--label=org.opencontainers.image.licenses=MPL-2.0"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ time \"2006-01-02T15:04:05Z07:00\" }}"
    image_templates:
      - "ghcr.io/liatrio/opentofu:{{ .Version }}-amd64"

  - use: buildx
    goarch: arm64
    goos: darwin
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.vendor=OpenTofu"
      - "--label=org.opencontainers.image.description=OpenTofu {{ .Version }}"
      - "--label=org.opencontainers.image.url=https://github.com/liatrio/opentofu"
      - "--label=org.opencontainers.image.documentation=https://github.com/liatrio/opentofu/blob/main/README.md"
      - "--label=org.opencontainers.image.source=https://github.com/liatrio/opentofu"
      - "--label=org.opencontainers.image.licenses=MPL-2.0"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ time \"2006-01-02T15:04:05Z07:00\" }}"
    image_templates:
      - "ghcr.io/liatrio/opentofu:{{ .Version }}-arm64"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

snapshot:
  name_template: "{{ .Version }}-next"

changelog:
  use: github-native

release:
  prerelease: auto
  draft: true
